#! /bin/bash


CARGO_TARGET=./target
CARGO_WEB_TARGET=./target_wasm32


function install_web_dependency {
    export CARGO_TARGET_DIR=$CARGO_WEB_TARGET

    rustup target add wasm32-unknown-unknown
    cargo install wasm-bindgen-cli
}

function build_web {
    export CARGO_TARGET_DIR=$CARGO_WEB_TARGET

    cargo build --example map_preview --target wasm32-unknown-unknown --features bevy_ecs_tilemap/atlas
    wasm-bindgen --out-dir ./website/ --out-name wasm --target web $CARGO_WEB_TARGET/wasm32-unknown-unknown/debug/examples/map_preview.wasm

    cp -r ./assets ./website/
}

function build_web_release {
    export CARGO_TARGET_DIR=$CARGO_WEB_TARGET

    cargo build --example map_preview --target wasm32-unknown-unknown --features bevy_ecs_tilemap/atlas --release
    wasm-bindgen --out-dir ./website/ --out-name wasm --target web $CARGO_WEB_TARGET/wasm32-unknown-unknown/release/examples/map_preview.wasm

    cp -r ./assets ./website/
}




command=$1; shift;
$command "$@"