
[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.test]
command = "cargo"
args = ["run", "--example", "map_preview"]


[tasks.map-preview]
command = "cargo"
args = ["run", "--example", "map_preview"]

[tasks.map-generation]
command = "cargo"
args = ["run", "--example", "map_generation"]

[tasks.dep-wasm]
script = [
    "rustup target add wasm32-unknown-unknown",
    "cargo install wasm-bindgen-cli"
]

[tasks.build-website]
script = [
    "cargo build --example map_preview --target wasm32-unknown-unknown --features bevy_ecs_tilemap/atlas $RELEASE",
    "wasm-bindgen --out-dir ./website/ --out-name wasm --target web $CARGO_WEB_TARGET/wasm32-unknown-unknown/$MODE_DIR/examples/map_preview.wasm",
    "cp -r ./assets ./website/"
]




[env]
CARGO_TARGET_DIR="./target"
MODE_DIR="debug"

[env.web]
CARGO_TARGET_DIR="./target_wasm32"

[env.release]
RELEASE="--release"
MODE_DIR="release"



