name: Test PR

on:
  push:
    pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1
      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('Cargo.lock') }}
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target_linux
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('Cargo.lock') }}
      - name: Dependency
        run: sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev && rustup component add rustfmt
      - name: Dependencies
        run: cargo vendor && cargo install --force cargo-make && cargo make dep-wasm --profile web
      - name: Test
        run: cargo make test
      - name: Style Check
        run: cargo make format
      - name: Build web
        run: cargo make build-website --profile web